@startuml



threadserver <|-- mainserver
Parse.Request <|-- Parse.parse
Parse.Response <|-- Parse.parse
Parse.parse <|-- threadserver
Parse.messages <|-- threadserver

class mainserver {
   main()
}

class threadserver {
 run()
}
class Parse.Request{
    private String method;

    private String url;

    private String version;

    private Map<String, String> headers;

    private String message;
}

class Parse.parse{
 buildResponse()
 parserequest()
}

class Parse.Response{
    private String version;
    private int code;
    private String status;

    private Map<String, String> headers;

    private String message;
}
class Parse.messages{
showMessages()
addMessages(String message)
SelectMessages(int index)
updateMessages(int index,String message)
DELETEMessages(int index)
}

@enduml